datasets:
  training: toluene_ccsd_t-train.npz
  test: toluene_ccsd_t-test.npz
    #validation:

md_engine: 
  name: lammps

models:
  example:
    engine: nequip
    path: /home/joan/anaconda3/envs/cp2k-workflows/bin/nequip
    config: example.yaml
  full: 
    engine: requip
    config: full.yaml
  

